import ToggleTheme from '@/components/theme/ToggleTheme'
import '../globals.css'
import AuthProvider from '@/lib/AuthProvider'

export const metadata = {
  title: 'Auth',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className='bg-black'>
        <AuthProvider>
        {children}
        </AuthProvider>
        </body>
    </html>
  )
}
