import EditThread from '@/components/forms/EditThread';
import { fetchThreadByIdEdit } from '@/lib/actions/thread.action';
import React from 'react'

export async function generateMetadata({ params, searchParams }) {
    // const userInfo = await fetchUser(params.id);
    return {
      title: `Edit Post`,
      description: "Generated by create next app",
    };
  }

const page = async ({params}) => {
  const thread = await fetchThreadByIdEdit(params.id)
    console.log(params.id)
  return (
    <>
    <h1 className='text-3xl font-bold text-black dark:text-gray-200 pb-5'>Edit Thread</h1>
    <EditThread thread={thread}/>
    </>
  )
}

export default page